default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: deploy2
  password: 123456123aKa

development:
  <<: *default
  database: myapp

test:
  <<: *default
  database: myapp

production:
  <<: *default
  database: myapp
  username: deploy2
  password: 123456123aKa
